name: dpi
channels:
- pytorch
- defaults
dependencies:
- jupyter
- nb_conda
- numpy
- pyyaml
- mkl
- setuptools
- cmake
- cffi
- pytorch=0.4
- matplotlib
- scikit-image
- scikit-learn
- torchvision
- termcolor
- pillow
- tqdm
- pip:
    - gputil